using UnityEngine;
using UnityEngine.InputSystem;

public class InventoryUIController : MonoBehaviour
{
	public DynamicInventoryDisplay chestPanel;
	public DynamicInventoryDisplay playerBackpackPanel;

	private void Awake()
	{
		chestPanel.gameObject.SetActive(false);
		playerBackpackPanel.gameObject.SetActive(false);
	}

	private void OnEnable()
	{
		InventoryHolder.OnDynamicInventoryDisplayRequested += DisplayInventory;
		PlayerInventoryHolder.OnPlayerBackPackDisplayRequested += DisplayPlayerBackpack;
	}

	private void OnDisable()
	{
		InventoryHolder.OnDynamicInventoryDisplayRequested -= DisplayInventory;
		PlayerInventoryHolder.OnPlayerBackPackDisplayRequested -= DisplayPlayerBackpack;
	}

	void Update()
	{
		if (chestPanel.gameObject.activeInHierarchy && Keyboard.current.escapeKey.wasPressedThisFrame)
			chestPanel.gameObject.SetActive(false);

		if (playerBackpackPanel.gameObject.activeInHierarchy && Keyboard.current.escapeKey.wasPressedThisFrame)
			playerBackpackPanel.gameObject.SetActive(false);
	}

	void DisplayInventory(InventorySystem invToDisplay)
	{
		chestPanel.gameObject.SetActive(true);
		chestPanel.RefreshDynamicInventory(invToDisplay);
	}

	void DisplayPlayerBackpack(InventorySystem invToDisplay)
	{
		playerBackpackPanel.gameObject.SetActive(true);
		playerBackpackPanel.RefreshDynamicInventory(invToDisplay);
	}
}